### Ansible ###
# @author Felix Angel Martinez Muela
---
- name: Ansible
  hosts: all
  remote_user: vagrant
  become: yes
  tasks:
  - name: do something in the shell
    shell: echo hello > /tmp/abc.txt
...