---
- name: Aprovisionar m치quinas
  hosts: all
  remote_user: vagrant
  become: yes
  tasks:
  ### Configure Corosync Cluster
  - name: Modificamos el fichero de configuraci칩n de corosync desde plantilla .j2
    template:
      src: templates/corosync.j2
      dest: /etc/corosync/corosync.conf
     
- name: Aprovisionar m치quinas
  hosts: all
  remote_user: vagrant
  become: yes
  tasks:
  - name: Creamos el fichero pcmk desde plantilla
    template:
      src: templates/pacemaker.conf
      dest: /etc/corosync/service.d/pcmk

  - name: Cambiar linea de configuraci칩n para iniciar corosync
    lineinfile:
      path: /etc/default/corosync
      regexp: '^START='
      line: 'START=yes'

  - name: Reiniciar el servicio corosync
    service:
      name: corosync
      state: restarted

  ### Start and Configure Pacemaker ###
  - name: Ejecutar pacemaker desde el inicio
    command: update-rc.d pacemaker defaults 20 01

  - name: Iniciar el servicio pacemaker
    service:
      name: pacemaker
      state: restarted

  - name: Comprobar estado nodos
    command: crm status
    register: crm_status
    failed_when: "('3 Nodes configured' or 'Online: [ nodo1 nodo2 nodo3 ]') not in crm_status.stdout"
  
  ### Configure Cluster Properties ###
  - name: Desactivar modo Stonith
    command: crm configure property stonith-enabled=false

  - name: Desactivar mensajes quorum en logs
    command: crm configure property no-quorum-policy=ignore
...
