---
- name: Aprovisionar máquinas
  hosts: nodo2, nodo3
  remote_user: vagrant
  become: yes
  tasks:
  - name: Instalar paquetes necesarios
    apt:
      update_cache: yes
      force_apt_get: yes
      name: "{{ item }}"
      state: latest
    loop:
      - libqb0
      - fence-agents
      - pacemaker
      - ntp

  ### Configure Firewall ###
  # Equivalente al comando: 
  # iptables -A INPUT  -i eth1 -p udp -m multiport --dports 5404,5405,5406 
  #          -m conntrack --ctstate NEW,ESTABLISHED -j ACCEPT
  - name: INPUT iptable
    iptables:
      chain: INPUT
      in_interface: eth1
      protocol: udp
      destination_port: "{{ item }}"
      ctstate: NEW,ESTABLISHED
      jump: ACCEPT
    loop:
      - 5404
      - 5405
      - 5406

  # Equivalente al comando:
  # iptables -A OUTPUT  -o eth1 -p udp -m multiport --sports 5404,5405,5406 
  #          -m conntrack --ctstate ESTABLISHED -j ACCEPT
  - name: OUTPUT iptable
    iptables:
      chain: OUTPUT
      out_interface: eth1
      protocol: udp
      source_port: "{{ item }}"
      ctstate: ESTABLISHED
      jump: ACCEPT
    loop:
      - 5404
      - 5405
      - 5406

  - name: Copiamos authkey de local al servidor secundario en /tmp
    copy:
      src: templates/authkey
      dest: /etc/corosync/
      owner: root
      mode: 400
...