# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Número de nodos que tendrá el cluster
  N_Machines = 3 # N Nodos >= 1 && <=9
  (1..N_Machines).each do |machine_id|
    if machine_id == 1 #Master
      config.vm.define "nodo#{machine_id}", primary: true, autostart: true do |node|
        # Provider
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = 2
          vb.name = "nodo#{machine_id}"
          vb.gui = false
        end
        # Image
        node.vm.box = "ubuntu/trusty64" # Ubuntu 14.04 LTS
        node.vm.boot_timeout = 600
        # Network
        node.vm.network "private_network", ip: "192.168.128.10#{machine_id}"
        # Sync folder
        node.vm.synced_folder "./shared_folders/master_shared_folder", "/home/vagrant/shared_file" # Master shared folder
        # Provision
        node.vm.provision "ansible" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "master_Ansible.yml"  # Posibilidad de añadir un playbook distinto al nodo maestro            
            ansible.host_key_checking = "false"            
            ansible.limit = "nodo#{machine_id}"
          end   
      end
    else  # Slave
      config.vm.define "nodo#{machine_id}",primary: false, autostart: true do |node|
        # Provider
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = 1
          vb.name = "nodo#{machine_id}"
          vb.gui = false
        end
        # Image
        node.vm.box = "ubuntu/trusty64" # Ubuntu 14.04 LTS
        node.vm.boot_timeout = 600
        # Network
        node.vm.network "private_network", ip: "192.168.128.10#{machine_id}"
        # Sync folder
        node.vm.synced_folder "./shared_folders/slave_shared_folder", "/home/vagrant/shared_file" # Slave shared folder
        # Provision all slaves at the same time
        if machine_id == N_Machines
          node.vm.provision "ansible" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "slave_Ansible.yml"  # Playbook propio de un esclavo            
            ansible.host_key_checking = "false"
            ansible.limit = "all:!nodo1"
          end
          # Aprovisionamiento con dependencias entre nodos máster y esclavos
          node.vm.provision "ansible" do |ansible|
            ansible.verbose = "v"
            ansible.playbook = "mixed_Ansible.yml"  # Playbook con jugadas mixtas            
            # Lanzamos el playbook sobre n nodos del cluster
            ansible.extra_vars = {
              CLUSTER_NODES_NUMBER: "#{N_Machines}"
            }
            ansible.host_key_checking = "false"
            ansible.limit = "all"
          end
        end
      end
    end        
  end
end
