# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!

# ¡Completa el archivo con las configuraciones que se indican en los comentarios de más abajo!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  # configura red privada con ip fijo
  config.vm.network :private_network, ip: "192.168.100.100"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    # referencia el archivo playbook
    ansible.playbook = "provision.yml"
    ansible.host_key_checking = "false"
    ansible.limit = "all"
  end
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
end
