---
- name: Aprovisionar m치quinas
  hosts: all
  remote_user: vagrant
  become: yes
  tasks:
  - include_vars: ./vars/main.yml
  - name: Modificamos el fichero de configuraci칩n de corosync desde plantilla .j2
    template:
      src: templates/corosync_felix.j2
      dest: /etc/corosync/corosync.conf   
  
- name: Aprovisionar m치quinas
  hosts: all
  remote_user: vagrant
  become: yes
  tasks:
  - include_vars: ./vars/main.yml
  - name: Creamos el fichero pcmk desde plantilla
    template:
      src: templates/pacemaker.conf
      dest: /etc/corosync/service.d/pcmk

  - name: Cambiar linea de configuraci칩n para iniciar corosync
    lineinfile:
      path: /etc/default/corosync
      regexp: '^START='
      line: 'Start=yes'

  - name: Reiniciar el servicio corosync
    service:
      name: corosync
      state: restarted

  ### Start and Configure Pacemaker ###
  - name:
    command: update-rc.d pacemaker defaults 20 01

  - name: Iniciar el servicio pacemaker
    service:
      name: pacemaker
      state: restarted
  

...